package su.levenetc.kbot

val hello = "Hello"
val helloBot = "Hello, Bot"
val howAreYou = "How are you?"
val okBye = "Ok. Bye!"
val fine = "Fine"
val aOrB = "A or B?"
val a = "A"
val b = "B"
val endA = "endA"
val endB = "endB"
val load = "load"
val questionID = "id?"
val id1 = "1"
val id2 = "2"
val id3 = "3"
val messageA = "messageA"
val messageB = "messageB"
val messageC = "messageC"
val messageD = "messageD"
val result = "result"